---
id: sinatrasapporo-20160619
base_name: introduction-of-webapp-debugging
tags:
  - sinatrasapporo
  - firefox
presentation_date: 2016/06/19
version: 2016.6.19.3
licenses:
  - CC0-1.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :md
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: 
  speaker_deck_user: 
